# Generated by Django 4.2.2 on 2023-06-26 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_game_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='pity',
            field=models.IntegerField(default=0),
        ),
    ]
