# Generated by Django 4.2.2 on 2023-06-27 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_rate_pity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='uploads/')),
                ('rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.rate')),
            ],
        ),
    ]
