# Generated by Django 4.2.2 on 2023-06-27 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='chance',
            field=models.FloatField(default=0),
        ),
    ]
