# Generated by Django 4.2.2 on 2023-06-27 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_item_chance'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='image',
            field=models.ImageField(default='abc', upload_to='game/uploads/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to='game/uploads/'),
        ),
    ]
