# Generated by Django 4.2.2 on 2023-06-27 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_game_image_alter_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='softpity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rate',
            name='softpitychance',
            field=models.FloatField(default=0),
        ),
    ]
