# Generated by Django 4.2.2 on 2023-06-27 21:22

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_rate_softpity_rate_softpitychance'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None),
        ),
    ]
