# Generated by Django 4.2.2 on 2023-06-30 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_rate_color'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rate',
            new_name='Rarity',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
