# Generated by Django 4.2.2 on 2023-06-30 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_rename_rate_rarity_delete_choice_delete_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='rate',
            new_name='rarity',
        ),
    ]
