# Generated by Django 4.2.2 on 2023-06-30 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_rename_rate_item_rarity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rarity',
            name='rarity',
            field=models.CharField(max_length=200),
        ),
    ]
