# Generated by Django 4.2.2 on 2023-06-30 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_alter_rarity_rarity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rarity',
            old_name='rarity',
            new_name='rarity_name',
        ),
    ]
